In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv(r'/content/drive/MyDrive/ksr_python/pandas/Pandas-main/Advanced_Dirty_Sales_Dataset.csv')
print(df.head(10))
print(df.tail(10))

   OrderID  CustomerID CustomerName   Product     Category Quantity    Price  \
0    44770        8192  @ charlie !  Keyboard  Electronics        1  $870.54
1    23355        9138  @ charlie !   Monitor  Electronics        5  $144.02
2    75847        4098  @ charlie !    Laptop  Accessories        3  $557.79
3    95176        2391      @ eva !   Monitor  Electronics        5   $552.2
4     1854        8842      @ eva !    Laptop  Accessories        4   $411.2
5    56788        6935    @ david !   Monitor  Electronics        1  $415.12
6    63473        2787      @ bob !    Tablet  Electronics        3   $677.7
7    79506        3389    @ alice !     Phone  Accessories        9  $674.73
8    55148        1287    @ david !    Laptop  Accessories        2  $330.38
9    24564        3745      @ bob !    Tablet  Accessories        8  $686.34

          OrderDate             City Region  Returned TotalAmount
0        32/13/2023      PHOENIX#123  South     False      870.54
1        05-02-2024      HOUSTON#123   West     False       720.1
2        11/08/2024     NEW YORK#123   East     False     1673.37
3        32/13/2023      CHICAGO#123  North     False      2761.0
4        32/13/2023      CHICAGO#123   East     False      1644.8
5  October 06, 2024  LOS ANGELES#123   West     False      415.12
6    April 03, 2024      PHOENIX#123   West     False      2033.1
7     July 14, 2024      HOUSTON#123  North      True     6072.57
8        09-01-2024      HOUSTON#123   East     False      660.76
9        23/04/2023      PHOENIX#123  North     False     5490.72
        OrderID  CustomerID CustomerName   Product     Category Quantity  \
100090    87473        6459      @ eva !     Phone  Electronics        7
100091    46252        4130      @ bob !     Phone  Accessories        7
100092     6769        5466      @ eva !  Keyboard  Accessories        3
100093    29838        8422      @ eva !   Monitor          NaN        8
100094    40937        2341      @ eva !    Tablet  Accessories        4
100095    95426        5376    @ alice !  Keyboard  Electronics        2
100096    77181        6047    @ alice !  Keyboard  Accessories        5
100097     7354        2439      @ bob !    Laptop  Electronics        8
100098    52126        2810    @ alice !  Keyboard  Electronics        7
100099    80766        5705    @ david !    Tablet  Electronics        1

           Price         OrderDate             City Region  Returned  \
100090    $971.5        12/10/2023      PHOENIX#123  South     False
100091   $348.02        2024-06-01      CHICAGO#123  South     False
100092   $752.28        2023-08-09  LOS ANGELES#123   West     False
100093   $302.33        09/04/2023      CHICAGO#123  South     False
100094   $736.55    March 12, 2024     NEW YORK#123   East      True
100095   $468.67        2023-08-14              NaN   West     False
100096  $1350.58        32/13/2023      CHICAGO#123  South      True
100097   $330.46        2024-10-05  LOS ANGELES#123   East     False
100098    $361.9  October 22, 2023     NEW YORK#123   West     False
100099   $760.99        26/03/2023      CHICAGO#123  North     False

       TotalAmount
100090      6800.5
100091     2436.14
100092     2256.84
100093     2418.64
100094      2946.2
100095      937.34
100096      6752.9
100097     2643.68
100098      2533.3
100099      760.99

In [ ]:
row = df.loc[df['City'].str.contains("LOS", case=False, na=False)].iloc[0]['City']

print(repr(row))
print([c for c in row])
print([hex(ord(c)) for c in row])

'LOS ANGELES#123'
['L', 'O', 'S', ' ', 'A', 'N', 'G', 'E', 'L', 'E', 'S', '#', '1', '2', '3']
['0x4c', '0x4f', '0x53', '0x20', '0x41', '0x4e', '0x47', '0x45', '0x4c', '0x45', '0x53', '0x23', '0x31', '0x32', '0x33']

Cleaning the data

In [ ]:
df['City'] = df['City'].str.replace(r'[^A-Za-z ]+', '', regex=True).str.strip()
df['CustomerName'] =  df['CustomerName'].str.replace(r'[^A-Za-z ]+', '', regex=True).str.strip()

df['Price'] = pd.to_numeric(df['Price'].astype(str).str.replace(r'[^\d.]+','',regex=True).str.strip(), errors='coerce')
df['OrderDate'] = pd.to_datetime(df['OrderDate'],errors="coerce", dayfirst=True)
df['TotalAmount'] = pd.to_numeric(df['TotalAmount'],errors='coerce')
df

/tmp/ipython-input-558300848.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['OrderDate'] = pd.to_datetime(df['OrderDate'],errors="coerce", dayfirst=True)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
0,44770,8192,charlie,Keyboard,Electronics,1,870.54,NaT,PHOENIX,South,False,870.54
1,23355,9138,charlie,Monitor,Electronics,5,144.02,2024-02-05,HOUSTON,West,False,720.10
2,75847,4098,charlie,Laptop,Accessories,3,557.79,2024-08-11,NEW YORK,East,False,1673.37
3,95176,2391,eva,Monitor,Electronics,5,552.20,NaT,CHICAGO,North,False,2761.00
4,1854,8842,eva,Laptop,Accessories,4,411.20,NaT,CHICAGO,East,False,1644.80
...,...,...,...,...,...,...,...,...,...,...,...,...
100095,95426,5376,alice,Keyboard,Electronics,2,468.67,2023-08-14,NaN,West,False,937.34
100096,77181,6047,alice,Keyboard,Accessories,5,1350.58,NaT,CHICAGO,South,True,6752.90
100097,7354,2439,bob,Laptop,Electronics,8,330.46,2024-10-05,LOS ANGELES,East,False,2643.68
100098,52126,2810,alice,Keyboard,Electronics,7,361.90,2023-10-22,NEW YORK,West,False,2533.30
100099,80766,5705,david,Tablet,Electronics,1,760.99,2023-03-26,CHICAGO,North,False,760.99

3. Convert OrderDate to datetime type.

In [ ]:
df['OrderDate']= pd.to_datetime(df['OrderDate'],errors='coerce')

In [ ]:
df.dtypes

OrderID                  int64
CustomerID               int64
CustomerName            object
Product                 object
Category                object
Quantity                object
Price                  float64
OrderDate       datetime64[ns]
City                    object
Region                  object
Returned                  bool
TotalAmount            float64
dtype: object

4. Display the total number of unique customers.

In [ ]:
df['CustomerID'].nunique()

8999

5. Show all unique product categories and count them.

In [ ]:
df['Product'].value_counts()

Product
Phone       19738
Laptop      19672
Keyboard    19626
Tablet      19551
Monitor     19512
Name: count, dtype: int64

6. Filter all orders made in the city of "Los Angeles".

In [ ]:
df[df['City']=='LOS ANGELES']

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
5,56788,6935,david,Monitor,Electronics,1,415.12,2024-10-06,LOS ANGELES,West,False,415.12
18,86339,3999,eva,Laptop,Electronics,9,1070.42,2024-04-29,LOS ANGELES,West,False,9633.78
19,64556,4509,charlie,Laptop,Electronics,1,1093.26,2024-05-21,LOS ANGELES,East,False,1093.26
21,87250,2818,alice,Phone,Electronics,3,1188.93,2024-02-27,LOS ANGELES,North,True,3566.79
25,79725,5498,eva,Tablet,Electronics,1,686.06,2023-09-24,LOS ANGELES,North,False,686.06
...,...,...,...,...,...,...,...,...,...,...,...,...
100078,17979,4338,eva,Monitor,Electronics,5,491.53,2024-09-23,LOS ANGELES,North,False,2457.65
100080,62097,3467,eva,Laptop,Accessories,4,274.01,NaT,LOS ANGELES,West,False,1096.04
100084,57768,5902,bob,Laptop,Electronics,9,618.35,NaT,LOS ANGELES,West,False,5565.15
100092,6769,5466,eva,Keyboard,Accessories,3,752.28,2023-08-09,LOS ANGELES,West,False,2256.84
100097,7354,2439,bob,Laptop,Electronics,8,330.46,2024-10-05,LOS ANGELES,East,False,2643.68

7. Select orders where quantity is more than 5.

In [ ]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')

In [ ]:
df[df['Quantity']>5]

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
7,79506,3389,alice,Phone,Accessories,9.0,674.73,2024-07-14,HOUSTON,North,True,6072.57
9,24564,3745,bob,Tablet,Accessories,8.0,686.34,2023-04-23,PHOENIX,North,False,5490.72
13,69640,1481,bob,Phone,Accessories,6.0,173.41,2023-11-26,HOUSTON,West,False,1040.46
17,23495,1514,bob,Tablet,Electronics,9.0,212.04,2023-07-09,CHICAGO,East,False,1908.36
18,86339,3999,eva,Laptop,Electronics,9.0,1070.42,2024-04-29,LOS ANGELES,West,False,9633.78
...,...,...,...,...,...,...,...,...,...,...,...,...
100090,87473,6459,eva,Phone,Electronics,7.0,971.50,2023-10-12,PHOENIX,South,False,6800.50
100091,46252,4130,bob,Phone,Accessories,7.0,348.02,2024-06-01,CHICAGO,South,False,2436.14
100093,29838,8422,eva,Monitor,NaN,8.0,302.33,2023-04-09,CHICAGO,South,False,2418.64
100097,7354,2439,bob,Laptop,Electronics,8.0,330.46,2024-10-05,LOS ANGELES,East,False,2643.68
100098,52126,2810,alice,Keyboard,Electronics,7.0,361.90,2023-10-22,NEW YORK,West,False,2533.30

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       100100 non-null  int64
 1   CustomerID    100100 non-null  int64
 2   CustomerName  100100 non-null  object
 3   Product       98099 non-null   object
 4   Category      98097 non-null   object
 5   Quantity      99099 non-null   float64
 6   Price         99099 non-null   float64
 7   OrderDate     80028 non-null   datetime64[ns]
 8   City          98098 non-null   object
 9   Region        100100 non-null  object
 10  Returned      100100 non-null  bool
 11  TotalAmount   99099 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(3), int64(2), object(5)
memory usage: 8.5+ MB

 Add a new column UnitTotal = Quantity * Price and compare with TotalAmount. Flag
mismatches.

In [ ]:
df['UnitTotal']= round(df['Quantity'] * df['Price'],2)
df['PrcFlag'] = df['UnitTotal'] == df['TotalAmount']
print(df[['OrderID','Quantity','UnitTotal','TotalAmount','PrcFlag']])

        OrderID  Quantity  UnitTotal  TotalAmount  PrcFlag
0         44770       1.0     870.54       870.54     True
1         23355       5.0     720.10       720.10     True
2         75847       3.0    1673.37      1673.37     True
3         95176       5.0    2761.00      2761.00     True
4          1854       4.0    1644.80      1644.80     True
...         ...       ...        ...          ...      ...
100095    95426       2.0     937.34       937.34     True
100096    77181       5.0    6752.90      6752.90     True
100097     7354       8.0    2643.68      2643.68     True
100098    52126       7.0    2533.30      2533.30     True
100099    80766       1.0     760.99       760.99     True

[100100 rows x 5 columns]

Create a new column DiscountApplied (True if UnitTotal > TotalAmount)

In [ ]:
df['DiscountApplied'] = df['UnitTotal'] > df['TotalAmount']
disc = df['DiscountApplied']
print(df['DiscountApplied'])

0         False
1         False
2         False
3         False
4         False
          ...
100095    False
100096    False
100097    False
100098    False
100099    False
Name: DiscountApplied, Length: 100100, dtype: bool

In [ ]:
df.drop(['DiscountApplied'],axis=1)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,PrcFlag
0,44770,8192,charlie,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX,South,False,870.54,870.54,True
1,23355,9138,charlie,Monitor,Electronics,5.0,144.02,2024-02-05,HOUSTON,West,False,720.10,720.10,True
2,75847,4098,charlie,Laptop,Accessories,3.0,557.79,2024-08-11,NEW YORK,East,False,1673.37,1673.37,True
3,95176,2391,eva,Monitor,Electronics,5.0,552.20,NaT,CHICAGO,North,False,2761.00,2761.00,True
4,1854,8842,eva,Laptop,Accessories,4.0,411.20,NaT,CHICAGO,East,False,1644.80,1644.80,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100095,95426,5376,alice,Keyboard,Electronics,2.0,468.67,2023-08-14,NaN,West,False,937.34,937.34,True
100096,77181,6047,alice,Keyboard,Accessories,5.0,1350.58,NaT,CHICAGO,South,True,6752.90,6752.90,True
100097,7354,2439,bob,Laptop,Electronics,8.0,330.46,2024-10-05,LOS ANGELES,East,False,2643.68,2643.68,True
100098,52126,2810,alice,Keyboard,Electronics,7.0,361.90,2023-10-22,NEW YORK,West,False,2533.30,2533.30,True
100099,80766,5705,david,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO,North,False,760.99,760.99,True

11. Filter all returned orders.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   OrderID          100100 non-null  int64
 1   CustomerID       100100 non-null  int64
 2   CustomerName     100100 non-null  object
 3   Product          98099 non-null   object
 4   Category         98097 non-null   object
 5   Quantity         99099 non-null   float64
 6   Price            99099 non-null   float64
 7   OrderDate        80028 non-null   datetime64[ns]
 8   City             98098 non-null   object
 9   Region           100100 non-null  object
 10  Returned         100100 non-null  bool
 11  TotalAmount      99099 non-null   float64
 12  UnitTotal        99099 non-null   float64
 13  PrcFlag          100100 non-null  bool
 14  DiscountApplied  100100 non-null  bool
dtypes: bool(3), datetime64[ns](1), float64(4), int64(2), object(5)
memory usage: 9.5+ MB

In [ ]:
df[df['Returned']== True]

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,PrcFlag,DiscountApplied
7,79506,3389,alice,Phone,Accessories,9.0,674.73,2024-07-14,HOUSTON,North,True,6072.57,6072.57,True,False
15,5103,1382,eva,Phone,Accessories,1.0,504.94,2023-03-07,NEW YORK,West,True,504.94,504.94,True,False
21,87250,2818,alice,Phone,Electronics,3.0,1188.93,2024-02-27,LOS ANGELES,North,True,3566.79,3566.79,True,False
31,81349,3421,eva,Laptop,Accessories,7.0,1383.91,2024-05-18,LOS ANGELES,West,True,9687.37,9687.37,True,False
53,50549,8174,eva,Monitor,Electronics,5.0,1358.43,NaT,HOUSTON,South,True,6792.15,6792.15,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100031,53849,7723,alice,Keyboard,Electronics,4.0,947.33,2023-04-14,CHICAGO,North,True,3789.32,3789.32,True,False
100041,94461,5550,charlie,Keyboard,Electronics,7.0,1479.18,2023-05-29,PHOENIX,East,True,10354.26,10354.26,True,False
100061,48148,6197,bob,Tablet,Accessories,3.0,670.62,2024-09-13,LOS ANGELES,South,True,2011.86,2011.86,True,False
100094,40937,2341,eva,Tablet,Accessories,4.0,736.55,2024-03-12,NEW YORK,East,True,2946.20,2946.20,True,False
100096,77181,6047,alice,Keyboard,Accessories,5.0,1350.58,NaT,CHICAGO,South,True,6752.90,6752.90,True,False

12. Show top 5 cities by number of orders.

In [ ]:
t5 = df['City'].value_counts()
t5.sort_values(ascending=False).head(5)

City
NEW YORK       19781
PHOENIX        19771
CHICAGO        19615
LOS ANGELES    19519
HOUSTON        19412
Name: count, dtype: int64

What are the top 3 most sold products (by quantity)?

In [ ]:
pt3  = df.groupby(['Product'])['Quantity'].sum()
pt3.sort_values(ascending=False)

Product
Phone       97697.0
Laptop      97501.0
Keyboard    96835.0
Tablet      96755.0
Monitor     95661.0
Name: Quantity, dtype: float64

In [ ]:
df = df.rename(columns={'CustomerName': 'CustName'})
print(df.head())
df = df.rename(columns={'CustName': 'CustomerName'})

   OrderID  CustomerID CustName   Product     Category  Quantity   Price  \
0    44770        8192  charlie  Keyboard  Electronics       1.0  870.54
1    23355        9138  charlie   Monitor  Electronics       5.0  144.02
2    75847        4098  charlie    Laptop  Accessories       3.0  557.79
3    95176        2391      eva   Monitor  Electronics       5.0  552.20
4     1854        8842      eva    Laptop  Accessories       4.0  411.20

   OrderDate      City Region  Returned  TotalAmount  UnitTotal  PrcFlag  \
0        NaT   PHOENIX  South     False       870.54     870.54     True
1 2024-02-05   HOUSTON   West     False       720.10     720.10     True
2 2024-08-11  NEW YORK   East     False      1673.37    1673.37     True
3        NaT   CHICAGO  North     False      2761.00    2761.00     True
4        NaT   CHICAGO   East     False      1644.80    1644.80     True

   DiscountApplied
0            False
1            False
2            False
3            False
4            False

15.Check and count missing values in each column.

In [ ]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'Product', 'Category',
       'Quantity', 'Price', 'OrderDate', 'City', 'Region', 'Returned',
       'TotalAmount', 'UnitTotal', 'PrcFlag', 'DiscountApplied'],
      dtype='object')

In [ ]:
df.isna().sum()

OrderID                0
CustomerID             0
CustomerName           0
Product             2001
Category            2003
Quantity            1001
Price               1001
OrderDate          20072
City                2002
Region                 0
Returned               0
TotalAmount         1001
UnitTotal           1001
PrcFlag                0
DiscountApplied        0
dtype: int64

16. Fill missing values in City (if any) with "Unknown"

In [ ]:
df['City'] = df['City'].fillna('Unknown')
print(df[df['City']=='Unknown'])

        OrderID  CustomerID CustomerName   Product     Category  Quantity  \
35        35505        3635        david   Monitor  Electronics       6.0
45        21246        7800          bob    Laptop  Electronics       2.0
74        70623        3593        alice     Phone  Accessories       4.0
112       74993        2653      charlie  Keyboard  Electronics       4.0
121       30876        4683          eva     Phone  Accessories       3.0
...         ...         ...          ...       ...          ...       ...
99810     32166        4315        david   Monitor  Electronics       9.0
99854      8586        2892        alice  Keyboard  Accessories       2.0
99894     61507        4914          eva    Laptop  Accessories       9.0
99949     53917        2590        alice    Laptop  Electronics       8.0
100095    95426        5376        alice  Keyboard  Electronics       2.0

          Price  OrderDate     City Region  Returned  TotalAmount  UnitTotal  \
35       391.90 2024-09-10  Unknown  North     False      2351.40    2351.40
45      1025.68 2023-05-09  Unknown   East     False      2051.36    2051.36
74      1171.19 2023-11-15  Unknown  South     False      4684.76    4684.76
112     1189.64 2024-12-19  Unknown  South     False      4758.56    4758.56
121     1211.18 2023-02-05  Unknown  South      True      3633.54    3633.54
...         ...        ...      ...    ...       ...          ...        ...
99810    280.01 2024-03-26  Unknown  North     False      2520.09    2520.09
99854    285.65 2024-10-22  Unknown  North     False       571.30     571.30
99894    729.34 2024-03-09  Unknown   East     False      6564.06    6564.06
99949   1060.05 2024-06-25  Unknown   East     False      8480.40    8480.40
100095   468.67 2023-08-14  Unknown   West     False       937.34     937.34

        PrcFlag  DiscountApplied
35         True            False
45         True            False
74         True            False
112        True            False
121        True            False
...         ...              ...
99810      True            False
99854      True            False
99894      True            False
99949      True            False
100095     True            False

[2002 rows x 15 columns]

17. Remove duplicates based on OrderID.

In [ ]:
df = df.drop_duplicates(subset='OrderID')

18. Sort the data by TotalAmount in descending order\

In [ ]:
df.sort_values('TotalAmount', ascending=False)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,PrcFlag,DiscountApplied
99875,78404,2864,bob,Laptop,Accessories,9.0,1499.99,2024-06-07,PHOENIX,West,False,13499.91,13499.91,True,False
47882,27909,1707,david,Monitor,Electronics,9.0,1499.95,2024-01-28,CHICAGO,West,False,13499.55,13499.55,True,False
75618,63782,7708,david,Keyboard,Electronics,9.0,1499.74,2024-06-07,NEW YORK,West,False,13497.66,13497.66,True,False
55578,49344,4338,david,Keyboard,Electronics,9.0,1499.20,2023-02-13,NEW YORK,South,False,13492.80,13492.80,True,False
53794,34029,3759,bob,Laptop,Electronics,9.0,1499.17,NaT,PHOENIX,East,False,13492.53,13492.53,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99302,6464,6738,david,Tablet,Electronics,NaN,NaN,2024-04-15,LOS ANGELES,North,False,NaN,NaN,False,False
99371,17207,5753,charlie,Phone,Electronics,NaN,NaN,NaT,HOUSTON,South,False,NaN,NaN,False,False
99529,29355,9833,eva,Keyboard,Accessories,NaN,NaN,2023-05-30,NEW YORK,West,False,NaN,NaN,False,False
99630,86382,8146,bob,Phone,Electronics,NaN,NaN,NaT,HOUSTON,East,False,NaN,NaN,False,False
99845,11862,8008,eva,Tablet,Electronics,NaN,NaN,2023-03-03,NEW YORK,North,False,NaN,NaN,False,False

19. Get the top 5 orders with the highest total amount

In [ ]:
df.sort_values('TotalAmount',ascending=False).head(5)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,PrcFlag,DiscountApplied
99875,78404,2864,bob,Laptop,Accessories,9.0,1499.99,2024-06-07,PHOENIX,West,False,13499.91,13499.91,True,False
47882,27909,1707,david,Monitor,Electronics,9.0,1499.95,2024-01-28,CHICAGO,West,False,13499.55,13499.55,True,False
75618,63782,7708,david,Keyboard,Electronics,9.0,1499.74,2024-06-07,NEW YORK,West,False,13497.66,13497.66,True,False
55578,49344,4338,david,Keyboard,Electronics,9.0,1499.20,2023-02-13,NEW YORK,South,False,13492.80,13492.80,True,False
53794,34029,3759,bob,Laptop,Electronics,9.0,1499.17,NaT,PHOENIX,East,False,13492.53,13492.53,True,False

20. Extract year and month from OrderDate.

In [ ]:
df['Order_Month'] = df['OrderDate'].dt.month_name()
df['Order_Year'] = df['OrderDate'].dt.year

print(df.head(5))

   OrderID  CustomerID CustomerName   Product     Category  Quantity   Price  \
0    44770        8192      charlie  Keyboard  Electronics       1.0  870.54
1    23355        9138      charlie   Monitor  Electronics       5.0  144.02
2    75847        4098      charlie    Laptop  Accessories       3.0  557.79
3    95176        2391          eva   Monitor  Electronics       5.0  552.20
4     1854        8842          eva    Laptop  Accessories       4.0  411.20

   OrderDate      City Region  Returned  TotalAmount  UnitTotal  PrcFlag  \
0        NaT   PHOENIX  South     False       870.54     870.54     True
1 2024-02-05   HOUSTON   West     False       720.10     720.10     True
2 2024-08-11  NEW YORK   East     False      1673.37    1673.37     True
3        NaT   CHICAGO  North     False      2761.00    2761.00     True
4        NaT   CHICAGO   East     False      1644.80    1644.80     True

   DiscountApplied Order_Month  Order_Year
0            False         NaN         NaN
1            False    February      2024.0
2            False      August      2024.0
3            False         NaN         NaN
4            False         NaN         NaN

22. Show all orders from Q1 of any year (Jan–Mar).

In [ ]:
df['Quarter'] = df['OrderDate'].dt.quarter

In [ ]:
df[df['Quarter']==1]

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,PrcFlag,DiscountApplied,Order_Month,Order_Year,Quarter
1,23355,9138,charlie,Monitor,Electronics,5.0,144.02,2024-02-05,HOUSTON,West,False,720.10,720.10,True,False,February,2024.0,1.0
8,55148,1287,david,Laptop,Accessories,2.0,330.38,2024-01-09,HOUSTON,East,False,660.76,660.76,True,False,January,2024.0,1.0
15,5103,1382,eva,Phone,Accessories,1.0,504.94,2023-03-07,NEW YORK,West,True,504.94,504.94,True,False,March,2023.0,1.0
21,87250,2818,alice,Phone,Electronics,3.0,1188.93,2024-02-27,LOS ANGELES,North,True,3566.79,3566.79,True,False,February,2024.0,1.0
24,90538,2124,david,Keyboard,Accessories,4.0,898.16,2023-01-03,PHOENIX,West,False,3592.64,3592.64,True,False,January,2023.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100069,47980,7443,alice,Laptop,Electronics,5.0,1344.51,2024-02-06,LOS ANGELES,East,False,6722.55,6722.55,True,False,February,2024.0,1.0
100074,79782,9365,david,Laptop,Accessories,5.0,1368.47,2023-01-12,LOS ANGELES,West,False,6842.35,6842.35,True,False,January,2023.0,1.0
100082,44707,7179,charlie,Keyboard,Electronics,9.0,1125.69,2023-02-22,PHOENIX,East,False,10131.21,10131.21,True,False,February,2023.0,1.0
100094,40937,2341,eva,Tablet,Accessories,4.0,736.55,2024-03-12,NEW YORK,East,True,2946.20,2946.20,True,False,March,2024.0,1.0
100099,80766,5705,david,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO,North,False,760.99,760.99,True,False,March,2023.0,1.0

23.Count number of orders for each region.

In [ ]:
df.groupby(['Region'])['OrderID'].count()

Region
East     25098
North    25022
South    24998
West     24882
Name: OrderID, dtype: int64

24.Display all customers who bought both "Phone" and "Laptop".

In [ ]:
df[df['Product'].isin(['Phone','Laptop'])][['CustomerID','CustomerName']]

        CustomerID CustomerName
2             4098      charlie
4             8842          eva
7             3389        alice
8             1287        david
10            6368        alice
...            ...          ...
100084        5902          bob
100087        3407          bob
100090        6459          eva
100091        4130          bob
100097        2439          bob

[39363 rows x 2 columns]

25.Convert all city names to uppercase and restore them back.

In [ ]:
df['City'] = df['City'].str.title()
print(df['City'].head(10))
df['City'] = df['City'] = df['City'].str.upper()
print(df['City'].head(10))
df['City'] = df['City'].str.title()
print(df['City'].head(10))

0        Phoenix
1        Houston
2       New York
3        Chicago
4        Chicago
5    Los Angeles
6        Phoenix
7        Houston
8        Houston
9        Phoenix
Name: City, dtype: object
0        PHOENIX
1        HOUSTON
2       NEW YORK
3        CHICAGO
4        CHICAGO
5    LOS ANGELES
6        PHOENIX
7        HOUSTON
8        HOUSTON
9        PHOENIX
Name: City, dtype: object
0        Phoenix
1        Houston
2       New York
3        Chicago
4        Chicago
5    Los Angeles
6        Phoenix
7        Houston
8        Houston
9        Phoenix
Name: City, dtype: object

26. Find average price of each category.

In [ ]:
df.groupby('Category').agg({'Price': 'mean'}).round(2)

              Price
Category
Accessories  801.42
Electronics  799.06

27.Use groupby() to find total sales by Region.

In [ ]:
df.loc[~df['Returned']].groupby('Region')['TotalAmount'].sum()

Region
East     89291155.03
North    88993956.48
South    89429812.85
West     88768557.23
Name: TotalAmount, dtype: float64

28. Save only East region data to a CSV file.

In [ ]:
df[df['Region']=='East'].to_csv('East.csv')

29. Reset and set index using OrderID.

In [ ]:
df = df.set_index('OrderID')
print(df.head(10))
df = df.reset_index()
print(df.head(10))

         CustomerID CustomerName   Product     Category  Quantity   Price  \
OrderID
44770          8192      charlie  Keyboard  Electronics       1.0  870.54
23355          9138      charlie   Monitor  Electronics       5.0  144.02
75847          4098      charlie    Laptop  Accessories       3.0  557.79
95176          2391          eva   Monitor  Electronics       5.0  552.20
1854           8842          eva    Laptop  Accessories       4.0  411.20
56788          6935        david   Monitor  Electronics       1.0  415.12
63473          2787          bob    Tablet  Electronics       3.0  677.70
79506          3389        alice     Phone  Accessories       9.0  674.73
55148          1287        david    Laptop  Accessories       2.0  330.38
24564          3745          bob    Tablet  Accessories       8.0  686.34

         OrderDate         City Region  Returned  TotalAmount  UnitTotal  \
OrderID
44770          NaT      Phoenix  South     False       870.54     870.54
23355   2024-02-05      Houston   West     False       720.10     720.10
75847   2024-08-11     New York   East     False      1673.37    1673.37
95176          NaT      Chicago  North     False      2761.00    2761.00
1854           NaT      Chicago   East     False      1644.80    1644.80
56788   2024-10-06  Los Angeles   West     False       415.12     415.12
63473   2024-04-03      Phoenix   West     False      2033.10    2033.10
79506   2024-07-14      Houston  North      True      6072.57    6072.57
55148   2024-01-09      Houston   East     False       660.76     660.76
24564   2023-04-23      Phoenix  North     False      5490.72    5490.72

         PrcFlag  DiscountApplied Order_Month  Order_Year  Quarter
OrderID
44770       True            False         NaN         NaN      NaN
23355       True            False    February      2024.0      1.0
75847       True            False      August      2024.0      3.0
95176       True            False         NaN         NaN      NaN
1854        True            False         NaN         NaN      NaN
56788       True            False     October      2024.0      4.0
63473       True            False       April      2024.0      2.0
79506       True            False        July      2024.0      3.0
55148       True            False     January      2024.0      1.0
24564       True            False       April      2023.0      2.0
   OrderID  CustomerID CustomerName   Product     Category  Quantity   Price  \
0    44770        8192      charlie  Keyboard  Electronics       1.0  870.54
1    23355        9138      charlie   Monitor  Electronics       5.0  144.02
2    75847        4098      charlie    Laptop  Accessories       3.0  557.79
3    95176        2391          eva   Monitor  Electronics       5.0  552.20
4     1854        8842          eva    Laptop  Accessories       4.0  411.20
5    56788        6935        david   Monitor  Electronics       1.0  415.12
6    63473        2787          bob    Tablet  Electronics       3.0  677.70
7    79506        3389        alice     Phone  Accessories       9.0  674.73
8    55148        1287        david    Laptop  Accessories       2.0  330.38
9    24564        3745          bob    Tablet  Accessories       8.0  686.34

   OrderDate         City Region  Returned  TotalAmount  UnitTotal  PrcFlag  \
0        NaT      Phoenix  South     False       870.54     870.54     True
1 2024-02-05      Houston   West     False       720.10     720.10     True
2 2024-08-11     New York   East     False      1673.37    1673.37     True
3        NaT      Chicago  North     False      2761.00    2761.00     True
4        NaT      Chicago   East     False      1644.80    1644.80     True
5 2024-10-06  Los Angeles   West     False       415.12     415.12     True
6 2024-04-03      Phoenix   West     False      2033.10    2033.10     True
7 2024-07-14      Houston  North      True      6072.57    6072.57     True
8 2024-01-09      Houston   East     False       660.76     660.76     True
9 2023-04-23      Phoenix  North     False      5490.72    5490.72     True

   DiscountApplied Order_Month  Order_Year  Quarter
0            False         NaN         NaN      NaN
1            False    February      2024.0      1.0
2            False      August      2024.0      3.0
3            False         NaN         NaN      NaN
4            False         NaN         NaN      NaN
5            False     October      2024.0      4.0
6            False       April      2024.0      2.0
7            False        July      2024.0      3.0
8            False     January      2024.0      1.0
9            False       April      2023.0      2.0

30.Display all orders placed on a weekend.

In [ ]:
df['week_day']=df['OrderDate'].dt.day_name()
print(df)

       OrderID  CustomerID CustomerName   Product     Category  Quantity  \
0        44770        8192      charlie  Keyboard  Electronics       1.0
1        23355        9138      charlie   Monitor  Electronics       5.0
2        75847        4098      charlie    Laptop  Accessories       3.0
3        95176        2391          eva   Monitor  Electronics       5.0
4         1854        8842          eva    Laptop  Accessories       4.0
...        ...         ...          ...       ...          ...       ...
99995    95426        5376        alice  Keyboard  Electronics       2.0
99996    77181        6047        alice  Keyboard  Accessories       5.0
99997     7354        2439          bob    Laptop  Electronics       8.0
99998    52126        2810        alice  Keyboard  Electronics       7.0
99999    80766        5705        david    Tablet  Electronics       1.0

         Price  OrderDate         City Region  Returned  TotalAmount  \
0       870.54        NaT      Phoenix  South     False       870.54
1       144.02 2024-02-05      Houston   West     False       720.10
2       557.79 2024-08-11     New York   East     False      1673.37
3       552.20        NaT      Chicago  North     False      2761.00
4       411.20        NaT      Chicago   East     False      1644.80
...        ...        ...          ...    ...       ...          ...
99995   468.67 2023-08-14      Unknown   West     False       937.34
99996  1350.58        NaT      Chicago  South      True      6752.90
99997   330.46 2024-10-05  Los Angeles   East     False      2643.68
99998   361.90 2023-10-22     New York   West     False      2533.30
99999   760.99 2023-03-26      Chicago  North     False       760.99

       UnitTotal  PrcFlag  DiscountApplied Order_Month  Order_Year  Quarter  \
0         870.54     True            False         NaN         NaN      NaN
1         720.10     True            False    February      2024.0      1.0
2        1673.37     True            False      August      2024.0      3.0
3        2761.00     True            False         NaN         NaN      NaN
4        1644.80     True            False         NaN         NaN      NaN
...          ...      ...              ...         ...         ...      ...
99995     937.34     True            False      August      2023.0      3.0
99996    6752.90     True            False         NaN         NaN      NaN
99997    2643.68     True            False     October      2024.0      4.0
99998    2533.30     True            False     October      2023.0      4.0
99999     760.99     True            False       March      2023.0      1.0

       week_day
0           NaN
1        Monday
2        Sunday
3           NaN
4           NaN
...         ...
99995    Monday
99996       NaN
99997  Saturday
99998    Sunday
99999    Sunday

[100000 rows x 19 columns]

In [ ]:
df[df['week_day'].isin(['Saturday','Sunday'])]

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,PrcFlag,DiscountApplied,Order_Month,Order_Year,Quarter,week_day
2,75847,4098,charlie,Laptop,Accessories,3.0,557.79,2024-08-11,New York,East,False,1673.37,1673.37,True,False,August,2024.0,3.0,Sunday
5,56788,6935,david,Monitor,Electronics,1.0,415.12,2024-10-06,Los Angeles,West,False,415.12,415.12,True,False,October,2024.0,4.0,Sunday
7,79506,3389,alice,Phone,Accessories,9.0,674.73,2024-07-14,Houston,North,True,6072.57,6072.57,True,False,July,2024.0,3.0,Sunday
9,24564,3745,bob,Tablet,Accessories,8.0,686.34,2023-04-23,Phoenix,North,False,5490.72,5490.72,True,False,April,2023.0,2.0,Sunday
11,36423,6745,charlie,Laptop,Electronics,4.0,188.80,2023-10-14,Houston,East,False,755.20,755.20,True,False,October,2023.0,4.0,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,46252,4130,bob,Phone,Accessories,7.0,348.02,2024-06-01,Chicago,South,False,2436.14,2436.14,True,False,June,2024.0,2.0,Saturday
99993,29838,8422,eva,Monitor,NaN,8.0,302.33,2023-04-09,Chicago,South,False,2418.64,2418.64,True,False,April,2023.0,2.0,Sunday
99997,7354,2439,bob,Laptop,Electronics,8.0,330.46,2024-10-05,Los Angeles,East,False,2643.68,2643.68,True,False,October,2024.0,4.0,Saturday
99998,52126,2810,alice,Keyboard,Electronics,7.0,361.90,2023-10-22,New York,West,False,2533.30,2533.30,True,False,October,2023.0,4.0,Sunday
99999,80766,5705,david,Tablet,Electronics,1.0,760.99,2023-03-26,Chicago,North,False,760.99,760.99,True,False,March,2023.0,1.0,Sunday

31.Create a pivot table of TotalAmount by Region and Category.

In [ ]:
piv = pd.pivot_table(
    df[df['Returned'] == False],
    index=['Region', 'Category'],
    values='TotalAmount',
    aggfunc=['sum', 'mean'],
    margins=True,
    margins_name='Grand Total'
).round(2)
piv

                                  sum        mean
                          TotalAmount TotalAmount
Region      Category
East        Accessories  4.335346e+07     3983.59
            Electronics  4.426087e+07     4012.04
North       Accessories  4.335492e+07     3971.69
            Electronics  4.364099e+07     3993.14
South       Accessories  4.390222e+07     4014.10
            Electronics  4.370137e+07     3989.53
West        Accessories  4.348296e+07     4034.42
            Electronics  4.359152e+07     3956.39
Grand Total              3.492883e+08     3994.29

32.Unpivot (melt) the pivot table from Task 31.

In [ ]:
piv2 = piv.reset_index()
piv2.index

RangeIndex(start=0, stop=9, step=1)

In [ ]:
piv2.columns = [
    col[0] if col[1] == '' else f"{col[0]}_{col[1]}"
    for col in piv2.columns
]
print(piv2.columns)

Index(['Region', 'Category', 'sum_TotalAmount', 'mean_TotalAmount'], dtype='object')

In [ ]:
melted = piv2.melt(
    id_vars=['Region', 'Category'],
    value_vars=['sum_TotalAmount', 'mean_TotalAmount'],
    var_name='Metric',
    value_name='TotalAmountValue'
)

In [ ]:
print(melted)

         Region     Category            Metric  TotalAmountValue
0          East  Accessories   sum_TotalAmount      4.335346e+07
1          East  Electronics   sum_TotalAmount      4.426087e+07
2         North  Accessories   sum_TotalAmount      4.335492e+07
3         North  Electronics   sum_TotalAmount      4.364099e+07
4         South  Accessories   sum_TotalAmount      4.390222e+07
5         South  Electronics   sum_TotalAmount      4.370137e+07
6          West  Accessories   sum_TotalAmount      4.348296e+07
7          West  Electronics   sum_TotalAmount      4.359152e+07
8   Grand Total                sum_TotalAmount      3.492883e+08
9          East  Accessories  mean_TotalAmount      3.983590e+03
10         East  Electronics  mean_TotalAmount      4.012040e+03
11        North  Accessories  mean_TotalAmount      3.971690e+03
12        North  Electronics  mean_TotalAmount      3.993140e+03
13        South  Accessories  mean_TotalAmount      4.014100e+03
14        South  Electronics  mean_TotalAmount      3.989530e+03
15         West  Accessories  mean_TotalAmount      4.034420e+03
16         West  Electronics  mean_TotalAmount      3.956390e+03
17  Grand Total               mean_TotalAmount      3.994290e+03

33.Use groupby() to get average Price by Product and Regio

In [ ]:
df.groupby(['Region', 'Product'])['Price'].mean()

Region  Product
East    Keyboard    792.649425
        Laptop      804.822406
        Monitor     802.998165
        Phone       793.711529
        Tablet      812.075704
North   Keyboard    799.906062
        Laptop      814.809734
        Monitor     788.871712
        Phone       800.648342
        Tablet      807.827802
South   Keyboard    802.524754
        Laptop      801.743241
        Monitor     793.018953
        Phone       805.597180
        Tablet      798.590844
West    Keyboard    792.697716
        Laptop      793.771419
        Monitor     803.615438
        Phone       801.076021
        Tablet      796.121233
Name: Price, dtype: float64

34.Use .agg() to get min, max, and mean quantity for each category.

In [ ]:
df.dtypes

OrderID                     int64
CustomerID                  int64
CustomerName               object
Product                    object
Category                   object
Quantity                  float64
Price                     float64
OrderDate          datetime64[ns]
City                       object
Region                     object
Returned                     bool
TotalAmount               float64
UnitTotal                 float64
PrcFlag                      bool
DiscountApplied              bool
Order_Month                object
Order_Year                float64
Quarter                   float64
week_day                   object
dtype: object

In [ ]:
df.groupby('Category')['Quantity'].agg(['min', 'max', 'mean'])

             min  max      mean
Category
Accessories  1.0  9.0  4.995242
Electronics  1.0  9.0  4.979252

5.Create a lookup table for CustomerID and CustomerName and remove duplicates.

In [ ]:
look_up = df[['CustomerID', 'CustomerName']].drop_duplicates()
print(look_up)

       CustomerID CustomerName
0            8192      charlie
1            9138      charlie
2            4098      charlie
3            2391          eva
4            8842          eva
...           ...          ...
99929        8276          bob
99954        4222          eva
99981        8960          bob
99989        6732          eva
99992        5466          eva

[40134 rows x 2 columns]

Create a lookup for Product and Category, remove duplicates.

In [ ]:
prod_cat_lookup =df[['Quantity','Category']].drop_duplicates()

In [ ]:
prod_cat_lookup = df[['Product', 'Category']].drop_duplicates()
display(prod_cat_lookup)

       Product     Category
0     Keyboard  Electronics
1      Monitor  Electronics
2       Laptop  Accessories
6       Tablet  Electronics
7        Phone  Accessories
9       Tablet  Accessories
11      Laptop  Electronics
14    Keyboard  Accessories
21       Phone  Electronics
32     Monitor  Accessories
77     Monitor          NaN
95         NaN  Accessories
127        NaN  Electronics
132     Tablet          NaN
151   Keyboard          NaN
240     Laptop          NaN
717      Phone          NaN
2207       NaN          NaN

37.Merge back the lookups with the main file (simulate master lookup join).

In [ ]:
df_merged = df.merge(look_up, on='CustomerID', how='left')

In [ ]:
df_merged = df_merged.merge(prod_cat_lookup,on ='Product',how='left')

38.Compare the original and merged DataFrames – are all rows retained?

In [ ]:
print(df.shape[0] == df_merged.shape[0])

False

39.Calculate return rate % by region (total returned orders / total orders).

In [ ]:
returned_by_reg = df.groupby('Region').agg(
    TotalOrders=('OrderID', 'count'),
    ReturnedOrders=('Returned', lambda x: x.sum())
)
returned_by_reg['Return Rate'] = returned_by_reg['ReturnedOrders'] /returned_by_reg['TotalOrders'] *100

In [ ]:
print(returned_by_reg)

        TotalOrders  ReturnedOrders  Return Rate
Region
East          25098            2533    10.092438
North         25022            2448     9.783391
South         24998            2438     9.752780
West          24882            2445     9.826381